

export enum RoomFlags {
    UP=1,
    RIGHT=2,
    CORNER_UP_RIGHT=3,
    DOWN=4,
    HALL_VERTICAL=5,
    CORNER_DOWN_RIGHT=6,
    INTERSECTION_VERT_RIGHT=7,
    LEFT=8,
    CORNER_UP_LEFT=9,
    HALL_HORIZONTAL=10,
    INTERSECTION_HORIZ_UP=11,
    CORNER_DOWN_LEFT=12,
    INTERSECTION_VERT_LEFT=13,
    INTERSECTION_HORIZ_DOWN=14,
    INTERSECTION_FULL=15,
}